apiVersion: v1 
kind: ReplicationController
metadata:
  name: guestbook
spec:
  selector:
    app: guestbook
  replicas: 3
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: linsun/guestbook:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        ports:
        - containerPort: 3000
          name: "http-server"