apiVersion: apps/v1
kind: Deployment
metadata:
  name: rethinkdb-driver
  namespace: default
  labels:
    db: rethinkdb-driver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rethinkdb-driver
  template:
    metadata:
      labels:
        app: rethinkdb-driver
    spec:
      spec:
      serviceAccountName: rethinkdb
      containers:
      - image: k8s.gcr.io/rethinkdb:1.16.0_1
        name: rethinkdb-driver
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
          name: admin-port
        - containerPort: 28015
          name: driver-port
        - containerPort: 29015
          name: cluster-port
        volumeMounts:
        - mountPath: /data/rethinkdb_data
          name: rethinkdb-storage
      volumes:
      - name: rethinkdb-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb-driver
spec:
  ports:
    - port: 28015
      targetPort: 28015
  selector:
    db: rethinkdb
