apiVersion: apps/v1
kind: Deployment
metadata:
  name: rethinkdb-admin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rethinkdb-admin
  template:
    metadata:
      labels:
        app: rethinkdb-admin
        db: rethinkdb
        role: admin
    spec:
      containers:
      - image: k8s.gcr.io/rethinkdb:1.16.0_1
        name: rethinkdb
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
          name: admin-port
        - containerPort: 28015
          name: driver-port
        - containerPort: 29015
          name: cluster-port
        volumeMounts:
        - mountPath: /data/rethinkdb_data
          name: rethinkdb-storage
      volumes:
      - name: rethinkdb-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb-admin
spec:
  ports:
   - port: 8080
     targetPort: 8080
  type: NodePort
  selector:
    db: rethinkdb
    role: admin