apiVersion: v1
kind: ServiceAccount
metadata:
  name: rethinkdb
  namespace: default
  labels:
    app.kubernetes.io/name: rethinkdb
    app.kubernetes.io/part-of: rethinkdb
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: rethinkdb
  namespace: default
  labels:
    app.kubernetes.io/name: rethinkdb
    app.kubernetes.io/part-of: rethinkdb
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: rethinkdb
  namespace: default
  labels:
    app.kubernetes.io/name: rethinkdb
    app.kubernetes.io/part-of: rethinkdb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rethinkdb
subjects:
  - kind: ServiceAccount
    name: rethinkdb
    namespace: default